In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.11.0+cpu


In [ ]:
#intro to tensors
#creating tensors
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as py int
scalar.item()

7

In [ ]:
#vector
vector =torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix =torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
tensor =torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.shape


torch.Size([1, 3, 3])

In [ ]:
tensor1 =torch.tensor([[[[1,2,3,1],[1,2,3,1],[1,1,2,3],[1,2,1,4],[1,1,2,3]]]])
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor.ndim

3

In [ ]:
#random tensor
# random tensors why since many neural networks start with a tensor full of random numberrs and then adjust those numbers to better represent the data

In [ ]:
#create a random tensor
random_tensor=torch.rand(3,4)
random_tensor
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor

tensor([[0.6877, 0.6521, 0.4457, 0.4252],
        [0.5701, 0.1747, 0.9349, 0.6809],
        [0.2907, 0.5201, 0.5116, 0.5172]])

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor =torch.rand(size=(224,224,3)) #width,height and colorchannel
random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor.shape


torch.Size([224, 224, 3])

In [ ]:
random_image_size_tensor

tensor([[[0.0454, 0.2584, 0.3211],
         [0.2369, 0.3852, 0.1802],
         [0.5072, 0.4343, 0.9273],
         ...,
         [0.4065, 0.5642, 0.0504],
         [0.4689, 0.4929, 0.2971],
         [0.1162, 0.5342, 0.7507]],

        [[0.8896, 0.3248, 0.1869],
         [0.7892, 0.1818, 0.3455],
         [0.4088, 0.7948, 0.5151],
         ...,
         [0.3390, 0.3313, 0.8471],
         [0.0301, 0.3887, 0.4126],
         [0.0636, 0.3436, 0.4241]],

        [[0.2753, 0.2798, 0.4677],
         [0.7146, 0.0692, 0.3692],
         [0.9121, 0.1981, 0.8908],
         ...,
         [0.9511, 0.0678, 0.7847],
         [0.9986, 0.4294, 0.3042],
         [0.8413, 0.3404, 0.5708]],

        ...,

        [[0.1984, 0.2102, 0.4149],
         [0.5370, 0.3878, 0.9655],
         [0.1009, 0.9338, 0.9328],
         ...,
         [0.4251, 0.9475, 0.4330],
         [0.5687, 0.2749, 0.9480],
         [0.5431, 0.0128, 0.3213]],

        [[0.6906, 0.1803, 0.7696],
         [0.6901, 0.5235, 0.2197],
         [0.

In [ ]:
##zeros and ones
#works best when you creating masks
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
tensor.dtype

torch.int64

In [ ]:
one = torch.ones(size=(3,4))
one
one.shape

torch.Size([3, 3, 4])

#creating a range of tensors


In [ ]:
#creating a range of tensors
onetoten =torch.arange(0,10)
onetoten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
onetoten =torch.arange(start=1,end=11,step=2)
onetoten


tensor([1, 3, 5, 7, 9])

#creating tensors like

In [ ]:
#creating tensor like
#it copies the shape of another tensor
ten_zeros= torch.zeros_like(onetoten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [ ]:
#float 32 tensor
#if you return the dtype it returns the float data type
#one of the big isses you run into in tensor is the tensors are not the same data type
# tensorsnot the right device
# tensors  not the right device
# tensors not he right data type
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
#incase to come across and issue with you tensor the surgical procedure is convert the data types from float 32 to float 16

float_16_tensor =float_32_tensor.type(torch.half)
float_16_tensor *float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.half)
int_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

#getting information from tensors
# tensorsnot the right device - to get information from a tensor use tensor.dtype
# tensors  not the right device - to get information from tenosr use tensor.shape
# tensors not he right data type - use tensor.device


In [ ]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0090, 0.0924, 0.9831, 0.1754],
        [0.3341, 0.3948, 0.3444, 0.5741],
        [0.1969, 0.4778, 0.3764, 0.4682]])

In [ ]:
#find out the details abouyt some tensor
print(some_tensor)
print(f"Datatype of tensor :{some_tensor.dtype}")
print(f"Shape of tensor :{some_tensor.shape}")
print(f"Device tensor is on :{some_tensor.device}")

tensor([[0.0090, 0.0924, 0.9831, 0.1754],
        [0.3341, 0.3948, 0.3444, 0.5741],
        [0.1969, 0.4778, 0.3764, 0.4682]])
Datatype of tensor :torch.float32
Shape of tensor :torch.Size([3, 4])
Device tensor is on :cpu


In [ ]:
#manipulating tensors(*/+-)
#create a tensor
tensor =torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
#trying the pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

#matrix multiplication
two main ways to perfoming mulitplication  on neural networks and deeplearning
1. element-wise multiplication
2 matrix-multliplcication(dot product)


In [ ]:
#element wise
tensor
tensor *tensor
print(tensor,"+",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) + tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
#Matrix multiplcation
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
#matrix mulitpication by hand
%%time
value =0
for i in range (len(tensor)):
  value +=tensor[i]* tensor[i]
  print (value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 4.48 ms, sys: 53 µs, total: 4.53 ms
Wall time: 13.1 ms


In [ ]:
#incomparision to tensor multiplication but torch function(torch.matmul())
%%time
torch.matmul(tensor,tensor)

CPU times: user 940 µs, sys: 0 ns, total: 940 µs
Wall time: 1.55 ms


tensor(14)

# one of the most common errors in deep learning
#   shape errors

#one of the
#rule1 of large matrix multiplication the inner dimmension must match
  # (3,2)@(3,2)-*wont work*
  # (3,2)@(2,3)-*will work*
  # (2,3)@(3,2)-*will work*




# #rule the resulting dimmension has the shape of the outer dimension
#  (2,3)@(3,2) ->(2,2)
# (3,2)@(2,3) ->(3,3)


In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))
#you release rule one applies

NameError: name 'torch' is not defined

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))


tensor([[0.1375, 0.0302, 0.0205],
        [0.3863, 0.0870, 0.0535],
        [0.1760, 0.0311, 0.0407]])

In [ ]:
import torch
tensor =torch.tensor([[[3,2,3],
                       [3,6,3],
                       [3,4,3]]])
torch.matmul(tensor,tensor)

tensor([[[24, 30, 24],
         [36, 54, 36],
         [30, 42, 30]]])